title: Article

status:
  draft: true
  unlisted: true
  listed: true

columns:
  - width: 2/3
    fields:
      category:
        width: 1/2
        label: Catégorie
        type: select
        options:
          multiples: Multiples
          papers: Papiers
          posters: Posters
          sounds: Sons
        default: normal  
      authors:
        width: 1/2
        label: Auteurs
        type: text
      intro:
        label: Intro
        type: textarea
      text:
        label: Texte
        type: textarea
      variants:
        label: Variantes
        type: structure
        fields:
          title:
            label: Nom
            type: text
          description:
            label: Description
            type: text
          price:
            label: Prix (€)
            step: .01
            type: number
            after: €
          tax:
            label: TVA (%)
            type: number
            default: 5.5
            step: .01
            after: %
          weight:
            label: Poids (g)
            type: number
            after: g
  - width: 1/3

    sections:
      infos:
        type: fields
        fields:
          soldout:
            label: Sold out
            type: toggle
          size:
            label: Affichage
            type: select
            options:
              normal: Normal
              double: Double
            default: normal  
          cover:
            label: Cover
            type: files
            min: 1
            max: 1
      gallery:
        type: files
        headline: Images
        template: image
